### ISSUE TITLE
7.2.0 is gone

### ISSUE THREAD

**Issue by taurauko** [bricolages/redshift_connector#10]
Thanks for building this gem!

There is a major issue with your latest update though.

The moment you pushed out 7.2.1, 7.2.0 seems to have disappeared from rubygems.

This causes all our builds to fail. Would it be possible to put it back on for compatibility reasons? We'll update to 7.2.1 asap, but not being able to run our builds for now is a very urgent problem.

## Logs
```
Fetching gem metadata from https://rubygems.org/.......
Could not find redshift-connector-7.2.0 in any of the sources
```

## Rubygems
![image](https://user-images.githubusercontent.com/26868233/43181131-87cf6418-9016-11e8-9529-83f1ae3002e3.png)
That `yanked` is probably the problem?

**Comment by aamine** [comment]
I'm very sorry for inconvenience!! As you say, I wrongly yanked latest version and I cannot repush it.  7.2.1 is completely same with 7.2.0, please use it

**Comment by taurauko** [comment]
I see. That seems to be rubygems.org's policy... Sad. Thanks for the quick response!
