### ISSUE TITLE
Rails 5.1 support?

### ISSUE THREAD

**Issue by davidstosik** [bricolages/redshift_connector#2]
[Rails 5.1 was released! 🎉 ](http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/)

But right now, even in its `rails5` branch, [this gems' gemspec](https://github.com/aamine/redshift-connector/blob/rails5/redshift-connector.gemspec#L19), as well as [activerecord5-redshift-adapter's gemspec](https://github.com/ConsultingMD/activerecord5-redshift-adapter/blob/master/activerecord5-redshift-adapter.gemspec#L18) both restrict activerecord to 5.0.x versions.

Are there issues with those gems working with Rails 5.1, or is it just a matter of loosening the version restrictions?

See related issue: https://github.com/ConsultingMD/activerecord5-redshift-adapter/issues/5

**Comment by aamine** [comment]
`~> 5.0` is equivalent to `>= 5.0 and < 6.0`, 5.1 is NOT restricted for this gem.
See https://robots.thoughtbot.com/rubys-pessimistic-operator

**Comment by davidstosik** [comment]
@aamine Oh, my bad! Thank you for your answer! 🙇

**Comment by taurauko** [comment]
@aamine activerecord5-redshift-adapter's gemspec changes are not reflected on rubygems though, so bundler can't pick it up without additional settings.

**Comment by aamine** [comment]
@taurauko I know but AR5 adapter is out of my control.  Talk to them directly
